### ISSUE TITLE
失败

### ISSUE THREAD

**Issue by wqzai** [WOLF4096/wolf_link#1]
不行![Snipaste_2022-02-07_00-48-10.png](https://s2.loli.net/2022/02/07/dxTRsIiXML9v7zE.png)

**Comment by WOLF4096** [comment]
使用方法：
1、新建数据库，执行sql文件中的创建表命令

将这一段内容放入sql执行

2、将网站文件放入网站根目录，修改index.php文件中的参数
输入主机ip，用户名，密码，库名

3、完成配置

狼链 - 短网址
http://0l6.cc/




***@***.***
 
发件人： 晚柒载
发送时间： 2022-02-07 00:51
收件人： WOLF4096/wolf_link
抄送： Subscribed
主题： [WOLF4096/wolf_link] 失败 (Issue #1)
不行
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
